### ISSUE TITLE
Feedback Social Network

### ISSUE THREAD

**Issue by brecabal** [scarleette/scl-2018-05-bc-core-pm-socialnetwork#17]
Estimadas @scarleette , Tamara, Natalia
Estuvimos revisando el proyecto entregado y tenemos algunos comentarios:

1. Buen trabajo, bien logrado

2. Importante tener una arquitectura de la información adecuada , en el que permita no sólo una estructura adecuada, sino también parte importante de cómo se va a ejecutar  mi código

3. Faltó tener una guía de estilos, test y mejorar la validación en HTML, usando mejor semantica y estructura.

4. Muy buen proyecto se notó  los resultados de una mejor planificación y colaboración en equipo. 

5. Feedback UX : No existen evidencias de test de usabilidad, no hay una definición de usos del color ni jerarquía de los elementos del sitio.

6. Las animo a trabajar la separación de responsabilidades en el código, si quieren saber más les dejo este es link [MVC](https://codigofacilito.com/articulos/mvc-model-view-controller-explicado)

**Comment by scarleette** [comment]
gracias Belén , sabemos que hay muchas cosas que mejorar y lo pondremos en practica en los próximos proyectos , agradecemos también el reconocer nuestros pequeños avances :)
